@startmindmap
'https://plantuml.com/mindmap-diagram

caption figure 1
title My super title

* <&globe>inscricoes
** Caes
** Hotel
** Banhos
* usuarios
** Clientes
** Funcionarios
** Administradores

header
My super header
endheader

center footer My super footer

legend right
  Short
  legend
endlegend
@endmindmap
